windows_x64_task:
  windows_container:
    cpu: 2
    memory: 2G
    dockerfile: .ci/windows_x64/Dockerfile
    os_version: 2019

  build_script:
    - dotnet publish -c Debug -r win-x64 --output build\Winter
    - ps: Compress-Archive -Path build\Winter -DestinationPath build\Winter.zip

  binaries_artifacts:
    path: build/Winter.zip
